### ISSUE TITLE
OFX / Vanguard Issues

### ISSUE THREAD

**Issue by qureous** [stoicflame/ofx4j#10]
Last week OFX responses from Vanguard started coming back empty. The response code is OK, but the response body is empty on the return InputStream OFXV1Connection.sendBuffer(URL, ByteArrayOutputStream).

If I send the same body via the standalone Postman app I get the correct OFX response body.

The Postman chrome app; ofx4j; command-line CURL and a couple other Java HTTP Client libraries all return response code 200 but an empty body.

Any ideas why this could be occurring or what else I could try to resolve this issue?

**Comment by stoicflame** [comment]
It's a problem with Vanguard. I'm afraid you'll have to take it up with them.
