### ISSUE TITLE
New tags are not available in the library

### ISSUE THREAD

**Issue by kasun90** [stoicflame/ofx4j#11]
I'm trying to use this library to interface with Turbo Tax. But Turbo Tax XML mapping has some tags which are not available in this library (Such as COLLECTIBLE tag for tax 1099). Will they be added later?

**Comment by stoicflame** [comment]
I'm happy to accept a pull request if you want to put one together!

**Comment by kasun90** [comment]
Can you please review above?

**Comment by stoicflame** [comment]
Included in version 1.9.

**Comment by kasun90** [comment]
This is not yet available in Maven central repo. Has it been pushed yet? Sorry to comment on an already closed issue.

**Comment by stoicflame** [comment]
It's there now.
