### ISSUE TITLE
how to set a custom clientUID?

### ISSUE THREAD

**Issue by fleminra** [stoicflame/ofx4j#17]
OFX4J novice here. Great library, thank you!

Is there a better way to set a custom client UID, than by extending `FinancialInstitutionImpl` and overriding `createSignonRequest()` (in Scala, sorry):

```scala
class CustomClientUIDFinancialInstitutionImpl(data: FinancialInstitutionData, connection: OFXConnection, clientUID: String)
  extends FinancialInstitutionImpl(data, connection) {

  override def createSignonRequest(username: String, password: String): SignonRequest = {
    val signonRequest= new SignonRequest
    signonRequest.setTimestamp(new Date)
    val fi = new FinancialInstitution
    fi.setId(getData.getFinancialInstitutionId)
    fi.setOrganization(getData.getOrganization)

    signonRequest.setClientUID(clientUID) // <<-----

    signonRequest.setFinancialInstitution(fi)
    signonRequest.setUserId(username)
    signonRequest.setPassword(password)
    signonRequest.setApplicationId(OFXApplicationContextHolder.getCurrentContext.getAppId)
    signonRequest.setApplicationVersion(OFXApplicationContextHolder.getCurrentContext.getAppVersion)

    signonRequest
  }
}
```

And then:
```scala
class CustomClientUIDFinancialInstitutionService extends FinancialInstitutionServiceImpl {
  def getFinancialInstitution(data: FinancialInstitutionData, clientUID: String): FinancialInstitution =
    if (data == null)
      null
    else
      new CustomClientUIDFinancialInstitutionImpl(data, getConnection(), clientUID)
}
```

Usage:
```scala
val fi = (new CustomClientUIDFinancialInstitutionService).getFinancialInstitution(data, clientUID)
```
Seems like there ought to be a way to do it that doesn't duplicate everything in `createSignonRequest()`.

(FWIW, Chase (credit cards) requires a custom client UID. They use it as a form of multi-factor authentication.)

**Comment by stoicflame** [comment]
Looks like a good candidate for an enhancement. Want to put together a pull request?

**Comment by fleminra** [comment]
Yep I can do that. I've tried it two different ways:

1. adding a second constructor
 `FinancialInstitutionImpl(FinancialInstitutionData data, OFXConnection connection, String clientUID)`
 (and invoking it from the original constructor), and a new method
 `FinancialInstitutionServiceImpl.getFinancialInstitution(FinancialInstitutionData data, String clientUID)`
 that uses it; and
2. adding a new method
 `FinancialInstitution.setClientUID(String clientUID)`.
 I didn't include a `FinancialInstitution.getClientUID()` because it's not useful to me at the moment, but it could be added for completeness.

It seems to me that the client UID is more similar to username and password than to `FinancialInstitutionData` — they're client-side values, not something characteristic of the F.I., so I lean toward <span>#</span>2 to keep client UID out of the `FinancialInstitution` construction process. It feels more natural to let the OFX4J-using code acquire the `FinancialInstitution` object in the normal way and then inject the client UID into it.

What do you think?

**Comment by stoicflame** [comment]
I'm good either way.

Thanks!
