### ISSUE TITLE
Getting an exception when calling readStatement and readProfile

### ISSUE THREAD

**Issue by crinklywrappr** [stoicflame/ofx4j#29]
Following the instructions on the README and seeing this error when calling readStatement or readProfile.

```
Required element 'LANGUAGE' (property 'language' of aggregate
com.webcohesion.ofx4j.domain.data.signon.SignonRequest) is null or empty
```

The prior steps all appear to work.

**Comment by ashgupta1489** [comment]
Certain fields are mandatory which were hard-coded in domain entities and removed in previous release.  [Refer toPull Request](https://github.com/stoicflame/ofx4j/pull/27/files)
You should be passing on the default value as  `Locale.US.getISO3Language().toUpperCase()` in `SignOnRequest ` object.

**Comment by crinklywrappr** [comment]
Hm.  I'm a bit confused on how to do that.

The classes in play are `FinancialInstitution`, `FinancialInstitutionData`, and `BankAccountDetails`.  I don't see eg `setSignOnRequest` on any of them.  I'm guessing I need to go way off the README rails to do this?

**Comment by ghe2014** [comment]
Add a line: 'signonRequest.setLanguage(Locale.US.getISO3Language().toUpperCase());' at the end of FinancialInstitutionImpl.createSignonRequest fixes this problem.  But I'm not sure if that's the best way to handle this problem.  Maybe the language attribute should be carried by FinancialInstition class. 

I'm going to stay with version 1.13 before someone has a better answer for this issue.
