### ISSUE TITLE
How to create a client and server with Authorized grant OAUTH flow for ofx? Please help

### ISSUE THREAD

**Issue by Manu355** [stoicflame/ofx4j#37]
Test server here shows change of init param to OFx v2. However for Authorised grant flow, where to set the token and create a server with OAUTH 2.0 flow end to end? Any help ASAP is appreciated.

<img width="367" alt="OAUTH_OFX_FLOW" src="https://user-images.githubusercontent.com/59342663/71561349-f976be80-2a3a-11ea-92d8-cf00d47548e9.png">

**Comment by stoicflame** [comment]
This project is for OFX, not OAuth. You'll need to look elsewhere to figure out how to implement OAuth on a server.

**Comment by Manu355** [comment]
ok Thanks. But does this project support ofx v2.2 implementation?
