### ISSUE TITLE
question: do you want updates to institutions.xml?

### ISSUE THREAD

**Issue by fleminra** [stoicflame/ofx4j#40]
I see that institutions.xml is 12 years old. Are you interested in pulling updates? I realize it's pretty volatile data and it's probably hopeless to keep it up-to-date. I wonder what most people are doing — keeping their own local changes to it? Or just storing the FI particulars outside of that file.

**Comment by fleminra** [comment]
I think maintaining this info at ofxhome.com would be more sustainable, but it's not clear whether any moderator/admin there is slurping up any updates from the conversations in their [Institution Errors](http://www.ofxhome.com/ofxforum//viewforum.php?id=5) forum.

**Comment by stoicflame** [comment]
If someone wants to take the time to update the file, I'm happy to merge a pull request. I agree that ofxhome.com would also be useful.
