### ISSUE TITLE
java.time support?

### ISSUE THREAD

**Issue by icecreamhead** [stoicflame/ofx4j#50]
Is there any plan/desire to add native support for the modern java.time datetime API rather than the deprecated java.util.Date API which it currently uses? One benefit would be the ability to support zone offset information in datetime fields.

**Comment by stoicflame** [comment]
Hi!

I don't personally have plans for the engagement, but If you'd like to put together a pull request I'd be happy to merge it.

**Comment by icecreamhead** [comment]
Great, I'll see how much work is involved. Thanks 👍
