### ISSUE TITLE
Currency should be a @ChildAggregate not an @Element in IncomeTransaction

### ISSUE THREAD

**Issue by simeonmalchev** [stoicflame/ofx4j#68]
Hi,
I think that Currency should be a @_ChildAggregate not an @_Element in IncomeTransaction. Currentrly, in IncomeTransaction there is this method:
```
  /**
   * Gets the currency code for the transaction. Only one of currency code or original currency
   * info should be set according to the OFX spec. If neither are set, means the default currency.
   * @see "Section 13.9.2.4.3, OFX Spec"
   *
   * @return the currency code for the transaction
   */
  @Element( name = "CURRENCY", order = 90)
  public String getCurrencyCode() {
    return currencyCode;
  }
```
I think the relevant OFX section is off by one, it seems to be "Section 13.9.2.4.4, OFX Spec", the one that concerns Currency in Income. And this section says:
```
<INCOME>
<INVTRAN> aggregate
<SECID> aggregate
<INCOMETYPE>
<TOTAL>
<SUBACCTSEC>
<SUBACCTFUND>
<TAXEXEMPT>
<WITHHOLDING>
<CURRENCY> aggregate
<ORIGCURRENCY> aggregate

Investment income is realized as cash into the investment account.
A negative TOTAL is used to denote adjustments to income.
```
The DTD of the spec also shows that CURRENCY and/or ORIGCURRENCY aggregates are allowed inside INCOME.
I found the OFX spec ^^ for v1.0.2 here: https://ofxorg.ocg-prod.a.intuit.com/downloads.html

**Comment by simeonmalchev** [comment]
I opened a pull request https://github.com/stoicflame/ofx4j/pull/69 please review. Note that I renamed `currencyCode` to `currencyInfo` in IncomeTransaction and InvestmentPosition as well as their respective getters/setters. Not sure whether this renaming was good.

**Comment by stoicflame** [comment]
Thanks for the PR!
