### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by victorcarvalhosp** [stoicflame/ofx4j#9]
Hello, when the ofx files has special characters like ã, é, í, (...) the character is replaced by a �...

So, how do I change the encoding type?

**Comment by raphaelfuchter** [comment]
I have the same problem

**Comment by stoicflame** [comment]
So it sounds like a bug.

If you want to put together a pull request with a fix, I'd be happy to merge and release.

**Comment by raphaelfuchter** [comment]
I solved this by putting the encoding type in the InputStream reading. Such that:

`InputStreamReader isr = new InputStreamReader(fileInputStream, Charset.forName("ISO-8859-1"));`
